# Generated by Django 5.0.7 on 2024-08-18 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_book_description_book_genres_book_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pages',
            field=models.TextField(blank=True, null=True),
        ),
    ]
