# Generated by Django 5.0.7 on 2024-08-18 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_book_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='number_of_books',
            field=models.IntegerField(default=0),
        ),
    ]
