# Generated by Django 5.0.7 on 2024-08-18 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_book_number_of_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genres',
            field=models.CharField(default='', max_length=255),
        ),
    ]
