# Generated by Django 5.0.7 on 2024-08-18 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_book_genres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='image_url_m',
        ),
        migrations.RemoveField(
            model_name='book',
            name='image_url_s',
        ),
    ]
