# Generated by Django 5.0.7 on 2024-08-18 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_remove_book_image_url_m_remove_book_image_url_s'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='new_column',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
