# Generated by Django 5.0.7 on 2024-08-20 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_book_new_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cart_books',
            field=models.ManyToManyField(blank=True, to='website.book'),
        ),
    ]
