# Generated by Django 5.0.7 on 2024-08-20 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_remove_product_binding_remove_product_book_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='new_column',
        ),
        migrations.AddField(
            model_name='product',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='website.book'),
        ),
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_products', to='website.profile'),
        ),
    ]
