# Generated by Django 5.0.7 on 2024-08-20 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_remove_product_new_column_product_book_product_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
