# Generated by Django 5.0.7 on 2024-08-20 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_delete_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='new_column',
        ),
        migrations.AddField(
            model_name='profile',
            name='book_product',
            field=models.ManyToManyField(blank=True, related_name='product_profiles', to='website.book'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cart_books',
            field=models.ManyToManyField(blank=True, related_name='cart_profiles', to='website.book'),
        ),
    ]
