# Generated by Django 5.0.7 on 2024-08-21 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_remove_book_new_column_profile_book_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='book_product',
            field=models.ManyToManyField(blank=True, related_name='profile_books', to='website.book'),
        ),
    ]
