# Generated by Django 5.0.7 on 2024-08-24 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_remove_profile_book_product_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderItem',
            new_name='ShoppingCart',
        ),
    ]
