# Generated by Django 5.0.7 on 2024-08-24 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_orderitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderItem',
            new_name='OrderItems',
        ),
    ]
